In [1]:
import numpy as np
np.__version__

'1.19.4'

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [7]:
# 產生 0 - 9 十個數字元素
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 產生 2, 4, 6, 8 數字元素; >=2 and <12; 每隔2
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [10]:
#浮點數序列; >=1.0 and <3.0; 每隔0.5
arange(1.0, 3.0, 0.5, dtype='float64')

array([1. , 1.5, 2. , 2.5])

當在 arange() 使用非整數的間隔值時，有可能會產生不一致的結果，如下例會有時會包含結束值但有時候不會。這時候可以考慮使用 linspace() 函式。

In [13]:
a = np.arange(0.13, 0.15, step=0.01)
print("沒有包含結束值:", a)
b = np.arange(0.12, 0.16, step=0.01)
print("包含結束值:", b)

沒有包含結束值: [0.13 0.14]
包含結束值: [0.12 0.13 0.14 0.15 0.16]


In [18]:
a = np.arange(2, 10, 2)
#b = np.linspace(2, 10, num=4, endpoint=False)
a
#b

array([2, 4, 6, 8])

建立多維陣列

In [21]:
#建立三維陣列
b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
             [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]
)

In [23]:
print (b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [24]:
#三維(2*4*3)
b.shape

(2, 4, 3)

In [25]:
#要查看多維陣列的維度數目，可以查看陣列的 ndim 屬性
b.ndim

3

In [28]:
# 隨機產生指定形狀的陣列
#二維(3*4)
np.random.rand(3, 4) #連續型均勻分布(0~1)

array([[0.58002875, 0.63805344, 0.27997272, 0.56855119],
       [0.47361401, 0.00849396, 0.01330825, 0.11767348],
       [0.74135166, 0.101275  , 0.90822017, 0.29224097]])

In [29]:
np.random.randn(3, 4) #常態分佈(-1, 1)

array([[ 0.65509028,  0.61032329,  0.38169431,  0.30006681],
       [ 0.33789494,  0.62233464,  1.25809267,  0.12658949],
       [ 1.33859127,  1.61131623, -0.7192509 ,  2.50669022]])

In [30]:
#隨機產生一維陣列的元素
np.random.random(10) #連續型均勻分布(0.0~1.0)

array([0.6521864 , 0.64437947, 0.34107765, 0.60448302, 0.45416547,
       0.35347639, 0.7571691 , 0.43867268, 0.60676196, 0.28280084])

In [31]:
#randint((low[, high, size, dtype])) #離散型均勻分布 #整數
np.random.randint(1,10, 5) # >=1 and <10; 5組元素 

array([4, 6, 6, 6, 9])

In [32]:
np.random.choice(100, 5) #<100; 5組元素

array([40, 18, 15, 11, 64])

In [33]:
#回傳的元素將不包含結束索引的元素
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

2. NumPy陣列的索引和切片 (Slicing)

In [34]:
a[5:10]

array([5, 6, 7, 8, 9])

In [36]:
a[5:10:2] # >=5, <10; 每隔2

array([5, 7, 9])

In [37]:
a[-1]

19

In [38]:
#切片如果只有給定 step 值為 -1 的話，則代表是反向取出，元素值是從最後一筆開始取出。
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [39]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b[1, 1]

5

In [50]:
b[:, 1:]

array([[2, 3],
       [5, 6]])