In [4]:
import numpy as np
np.__version__

'1.19.4'

In [5]:
a = np.array([[ 0,  1,  2,  3], 
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

透過 flatten() 與 ravel() 均可將多維陣列轉形為一維陣列，flatten() 與 ravel() 的使用透過下列兩種方法，得到的結果都是完全一樣的。

In [7]:
#轉形為一維陣列
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

與 flatten() 不同的是，ravel() 建立的是原來陣列的 view，所以在 ravel() 回傳物件中做的元素值變更，將會影響原陣列的元素值。

In [8]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
#改變b陣列的元素值
b[3] = 100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [11]:
a

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

flatten() 與 ravel() 引數 order 預設值為 C，常用的引數值有 C 和 F。C 的意義是 C-style，展開時是以 row 為主的順序展開；而 F 是 Fortran-style，展開時是以 column 為主的順序展開。

In [12]:
#C 的意義是 C-style，展開時是以 row 為主的順序展開
a.ravel(order='c') #以row來排序

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [13]:
# F 是 Fortran-style，展開時是以 column 為主的順序展開
a.ravel(order='F') #以column來排序

array([  0,   4,   8,   1,   5,   9,   2,   6,  10, 100,   7,  11])

1.2 reshape()
reshape() 的使用，可以透過 np.reshape(a, new_shape) 或 a.reshape(new_shape, refcheck=True) 來執行。

In [15]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a.reshape((5,3)) #如果新的總數與原先 shape 總數不一致的話，則會產生錯誤。

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
a.size

15

In [18]:
#Reshape 時，新的形狀可以採用模糊指定為 -1，讓 NumPy 自動計算。
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

1.3 resize()
resize() 的使用，也同樣可以透過 np.resize(a, new_shape) 或 a.resize(new_shape, refcheck=True) 來執行。

要改變被 reference 的陣列時有可能會產生錯誤，這時候可以將 refcheck 引數設為 False (預設為 True)。

In [19]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
b.size

15

In [22]:
#如果 resize 的大小超過總元素值(原本為3*5)，則會在後面的元素值的指定為 0。
b.resize((3,6),refcheck=False)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  0,  0]])

In [24]:
#如果 resize 的大小小於總元素值，則會依照 C-style 的順序，取得 resize 後的陣列元素。
b.resize(3, refcheck=False) #以row來排序
b

array([0, 1, 2])

2. 軸 (axis) 與維度 (dimension)
軸 (axis) 在 NumPy 多維陣列中是很重要觀念，但是在應用上容易混淆。軸的數目也就是 NumPy 陣列的維度 (dimension) 數，軸的順序編號從 0 開始

In [25]:
#2.1 一維陣列的軸
#對一維陣列來說，只有一個軸，所以 axis 為 0
a = np.array([1, 2, 3]) #axis=0
a

array([1, 2, 3])

In [26]:
#2.2 二維陣列的軸
#二維陣列的 ndim 為 2，也就是會有 2 個軸
#軸 0 就是沿著 row 的軸
#軸 1 是沿著 column 的軸
a = np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

2.3 三維陣列的軸
三維陣列有 3 個軸。可以理解軸的順序是"由外而內"、"由row而column"。

以前一天範例程式中三維陣列的例子來看，可以理解為 2 個 4 \times× 3 的二維陣列排在一起。

In [27]:
#由外而內
#由row而column
#2*4*3
#三維陣列
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
              [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
#查詢多維陣列中的軸
a.shape #2*4*3

(2, 4, 3)

In [30]:
#沿軸對元素做加總，call sum()函式並指定axis
a.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [31]:
#沿軸對元素做加總，call sum()函式並指定axis
a.sum(axis=1)

array([[22, 26, 30],
       [22, 26, 30]])

In [32]:
#沿軸對元素做加總，call sum()函式並指定axis
a.sum(axis=2)

array([[ 6, 15, 24, 33],
       [ 6, 15, 24, 33]])

3. NumPy 陣列的合併與分割

In [33]:
#np.reshape(a, new_shape, order='C') #按row排序
#np.reshape(a, new_shape, order='F') #按column排序
a = np.arange(10).reshape(5,2) #5*2陣列
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
#np.reshape(a, new_shape, order='C') #按row排序
#np.reshape(a, new_shape, order='F') #按column排序
b = np.arange(6).reshape(3,2) #3*2陣列
b

array([[0, 1],
       [2, 3],
       [4, 5]])

3.1 合併：concatenate(), stack(), hstack(), vstack()
使用 concatenate() 進行陣列的合併時，須留意除了指定的軸之外 (預設為 axis 0)
其他軸的形狀必須完全相同，合併才不會發生錯誤。

In [35]:
#numpy.concatenate((a1, a2, ...), axis=0, out=None)
np.concatenate((a, b)) #合併兩個陣列

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [36]:
np.concatenate((b, a)) #合併兩個陣列

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
c = np.arange(10).reshape(5, 2) #5*2陣列
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
#numpy.stack(arrays, axis=0, out=None)
#根據指定的軸進行合併

np.stack((a, c), axis=1) #根據axis=1合併兩個陣列

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [38]:
#numpy.stack(arrays, axis=0, out=None)
#根據指定的軸進行合併
np.stack((a, c), axis=0) #根據axis=0合併兩個陣列

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]])

In [41]:
#numpy.hstack(tup)
#根據水平軸進行合併
#除了指定的軸之外，其他軸的形狀必須完全相同才可以合併。
np.hstack((a, c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [42]:
#numpy.vstack(tup)
#根據垂直軸進行合併
#除了指定的軸之外，其他軸的形狀必須完全相同才可以合併。
np.vstack((a, c))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
#numpy.vstack(tup)
#根據垂直軸進行合併
#除了指定的軸之外，其他軸的形狀必須完全相同才可以合併。
np.vstack((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

3.2 分割

In [44]:
a = np.arange(10).reshape(5, 2) #5*2陣列
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
#split()
#numpy.split(array, indices_or_sections, axis=0)
#依axis=0等分split
np.split(a, 5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

4. 迭代
一維陣列的迭代，跟 Python 集合型別 (例如 List) 的迭代相同

In [46]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [47]:
for i in a:
    print(i)

0
1
2
3
4


In [48]:
#多維陣列的迭代則以 axis 0 為準。下面以二維陣列為例，列出各 row 的元素。
b = np.arange(6).reshape(2, 3) #2*3陣列
b

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
for row in b: ##多維陣列的迭代則以 axis=0 為準
    print(row)

[0 1 2]
[3 4 5]


In [50]:
#如果要列出多維陣列所有元素的話，可以配合 flat 屬性
for row in b.flat: #配合 flat 屬性
    print(row)

0
1
2
3
4
5


5. 搜尋與排序

In [51]:
#5.1 顯示最大值和最小值
#numpy.amax(array, axis=None, keepdims=)
#numpy.amin(array, axis=None, keepdims=)
a = np.random.randint(1, 20, 10) #>=1 and <20,挑10組
a

array([11,  4, 12,  1,  9,  9, 10,  5, 18, 13])

In [53]:
#陣列中最大的元素
#numpy.amax(array, axis=None, keepdims=)
np.amax(a)

18

In [54]:
#陣列中最小的元素
#numpy.amin(array, axis=None, keepdims=)
np.amin(a)

1

In [55]:
#如果是多維陣列的話，用法也是相同，也可以依照軸列出最大或最小值。
b = a.reshape(2, 5) #2*5陣列
b

array([[11,  4, 12,  1,  9],
       [ 9, 10,  5, 18, 13]])

In [56]:
# 若設定 keepdims=True，結果會保留原陣列的維度來顯示。
#numpy.amax(array, axis=None, keepdims=)
np.amax(b, keepdims=True)

array([[18]])

In [61]:
# 若設定 keepdims=False，結果不會保留原陣列的維度來顯示。
#numpy.amax(array, axis=None, keepdims=)
np.amax(b, keepdims=False)

18

In [62]:
#列出各row最大值
#ndarray.max(axis=None, keepdims=False)
b.max(axis=0)

array([11, 10, 12, 18, 13])

In [63]:
#列出各row最大值
#ndarray.max(axis=None, keepdims=False)
b.max(axis=1)

array([12, 18])

In [64]:
# 同樣的 amax 也可以依軸列出各 row 最大值
#numpy.amax(array, axis=None, keepdims=)
np.amax(b, axis=0)

array([11, 10, 12, 18, 13])

In [65]:
# 同樣的 amax 也可以依軸列出各 row 最大值
#numpy.amax(array, axis=None, keepdims=)
np.amax(b, axis=1)

array([12, 18])

In [66]:
#ndarray.min(axis=None, keepdims=False)
# 列出各 column 最小值
b.min(axis=0)

array([9, 4, 5, 1, 9])

5.2 顯示最大值和最小值的索引

In [67]:
np.random.seed(0)
a = np.random.randint(1, 20, size=(3, 4)) #>=1 and <20; 3*4陣列
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [68]:
#若沒有指定軸的話，argmax() 與 argmin() 會回傳多維陣列展平後的索引。
#numpy.argmax(array, axis=None)
np.argmax(a)

7

In [69]:
#numpy.argmin(array, axis=None)
np.argmin(a) #沒有指定軸axis的話, 回傳多維陣列展平後的索引

2

In [70]:
# 列出各 column 的最大值索引
#numpy.argmax(array, axis=None)
np.argmax(a, axis=0)

array([0, 0, 2, 1], dtype=int64)

In [71]:
# 列出各 row 的最大值索引
#numpy.argmax(array, axis=None)
np.argmax(a, axis=1)

array([1, 3, 2], dtype=int64)

In [72]:
# 元素值 1 為最小值，展平後的索引值為 2。
#ndarray.argmin(axis=None)
a.argmin() ##沒有指定軸axis的話, 回傳多維陣列展平後的索引

2

In [73]:
#ndarray.argmin(axis=None)
# 列出各 column 的最小值索引
a.argmin(axis=0)

array([1, 2, 0, 2], dtype=int64)

In [74]:
#ndarray.argmin(axis=None)
# 列出各 row 的最小值索引
a.argmin(axis=1)

array([2, 0, 3], dtype=int64)

5.3 找出符合條件的元素

In [75]:
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [76]:
#numpy.where(condition[, x, y])
#傳入條件式，回傳值為符合條件的元素索引
#以下面二維陣列為例，回傳的索引陣列要合併一起看
np.where(a > 10)
#以下均大於10
#a[0,0]=13
#a[0,1]=16
#a[1,3]=19
#a[2,2]=13

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 3, 2], dtype=int64))

In [77]:
#若是設定 x, y 引數的話，可將各元素取代掉
#如果元素值大於 10 的話就用 "Y" 來替代，反之則是 "N"
np.where(a > 10, "Y", "N")

array([['Y', 'Y', 'N', 'N'],
       ['N', 'N', 'N', 'Y'],
       ['N', 'N', 'Y', 'N']], dtype='<U1')

5.4 nonzero
nonzero 等同於 np.where(array != 0) 的語法
回傳符合非 0 條件的元素索引值

In [92]:
np.random.seed(2)
a = np.random.randint(0, 5, 10) #>=0 and <5; 挑10組
a

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [93]:
#numpy.nonzero(array)
np.nonzero(a)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [94]:
#ndarray.nonzero()
a.nonzero()

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

5.5 排序
要對陣列進行排序可以使用 sort() 與 argsort()
sort() 回傳的是排序後的陣列
argsort() 回傳的是排序後的陣列索引值

In [103]:
np.random.seed(3)
a = np.random.randint(0, 20, 10) #>=0 and <20; 挑出10組
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [104]:
#numpy.sort(a, axis=-1, kind=None, order=None)
np.sort(a)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [106]:
#ndarray.argsort()
a.argsort()

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4], dtype=int64)

In [109]:
#陣列物件.sort() 的語法會進行 in-place 排序，也就是原本的陣列內容會跟著改變
#ndarray.sort()
a.sort()
a

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [110]:
#多維陣列在排序時可以指定要依據的軸
b = np.random.randint(0, 20, size=(5, 4)) #>=0 and <20; 5*4陣列
b

array([[ 0, 12,  7, 14],
       [17,  2,  2,  1],
       [19,  5,  8, 14],
       [ 1, 10,  7, 11],
       [ 1, 15, 16,  5]])

In [111]:
#numpy.sort(a, axis=-1, kind=None, order=None)
np.sort(b, axis=0) #各 column排序

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])

In [112]:
#numpy.sort(a, axis=-1, kind=None, order=None)
np.sort(b, axis=1) #各row排序

array([[ 0,  7, 12, 14],
       [ 1,  2,  2, 17],
       [ 5,  8, 14, 19],
       [ 1,  7, 10, 11],
       [ 1,  5, 15, 16]])

排序支援多種不同的排序算法，包括 quicksort (預設)、heapsort、mergesort、timesort，在 kind 引數指定即可。依照官網文件指出排序速度是以 quicksort 最快，mergesort / timesort 其次，之後是 heapsort。

In [114]:
c = np.random.randint(0, 100000000, 1000000) #>=0 and <100000000;挑出100,000組
c

array([47497106, 31220863, 90851983, ..., 84865679, 58988382, 27070588])

In [115]:
#numpy.sort(a, axis=-1, kind=None, order=None)
np.sort(c, kind='heapsort')

array([      26,       58,       66, ..., 99999884, 99999914, 99999944])