In [29]:
import numpy as np

In [ ]:
#np.add(a, b) #加法
#np.substract(a, b) #減法
#np.multiply(a, b) #乘法
#np.divide(a, b) #除法
#np.mod(a, b) #求餘數

運算的時候，陣列的形狀 (shape) 必須相同，
或是遵循廣播 (broadcastiing) 規則，才能正確進行 element-wise 運算

In [4]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 2, 2, 2])

In [5]:
a + b

array([3, 4, 5, 6, 7])

In [6]:
#呼叫函式進行加法
np.add(a, b)

array([3, 4, 5, 6, 7])

In [7]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
d = 3

廣播 (broadcastiing) 規則:
a. 兩個陣列形狀完全相同
b. 比較兩個陣列的維度，如果維度的形狀相同的話，可以進行廣播
c. 比較兩個陣列的維度，其中一個維度為1的話，可以進行廣播

In [9]:
#若是兩個陣列形狀不相同的話，遵循廣播規則，下面的例子可以正常運算
c * d #其中一個維度為1的話，可以進行廣播

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
e = np.random.randint(1, 10, 20).reshape(2, 10) #>=1 and <10, 挑出20組; 2*10陣列
e

array([[6, 5, 3, 5, 8, 7, 1, 7, 6, 7],
       [1, 7, 6, 9, 6, 7, 5, 7, 6, 9]])

In [11]:
##其中一個維度為1的話，可以進行廣播
c + e

array([[ 6,  6,  5,  8, 12, 12,  7, 14, 14, 16],
       [ 1,  8,  8, 12, 10, 12, 11, 14, 14, 18]])

3. sum()
sum() 函式可以根據依指定的軸計算陣列元素值加總

In [12]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
#若沒有指定軸的話，則是回傳所有元素加總值
a.sum()

45

In [14]:
#numpy.sum()
np.sum(a, axis=0)

array([ 5,  7,  9, 11, 13])

In [15]:
#numpy.sum()
np.sum(a, axis=1)

array([10, 35])

3. 次方
方的運算，跟四則運算一樣，也要遵循上述的規則，才能成功進行運算
np.power(a, b)
a**b

In [16]:
#np.power(a, b)
#與2**3 相同
np.power(2, 3)

8

In [17]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
b

array([2, 2, 2, 2, 2])

In [19]:
#a 和 b形狀相同
np.power(a, b)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

In [20]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
e

array([[6, 5, 3, 5, 8, 7, 1, 7, 6, 7],
       [1, 7, 6, 9, 6, 7, 5, 7, 6, 9]])

In [23]:
# e 和 c 的次方運算符合廣播規則
e ** c

array([[        1,         5,         9,       125,      4096,     16807,
                1,    823543,   1679616,  40353607],
       [        1,         7,        36,       729,      1296,     16807,
            15625,    823543,   1679616, 387420489]], dtype=int32)

4. 平方根
np.sqrt()

In [24]:
#np.sqrt() 平方根
np.sqrt(4)

2.0

In [25]:
#np.sqrt() 平方根
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

6. 對數函式
np.log(x) #底數為e
np.log2(x) #底數為2
np.log10(x) #底數為10
np.log1p(x) #底數為e，計算log(1+x)

In [34]:
# 以 np.log10() 為例
f = np.array([1, 10, 100, 1000, 10000])
f

array([    1,    10,   100,  1000, 10000])

In [35]:
# 以 np.log10() 為例
np.log10(f)

array([0., 1., 2., 3., 4.])

7. 取近似值
round(), around() 
在 Rounding 的方法部分，與 Python 同樣採用 IEEE 754 規範，
四捨、五取最近偶數、六入，而非我們一般講的四捨五入。

round(), around() #四捨、五取最近偶數、六入
rint() #Round至最近的整數
trunc() #無條件捨去小數點
floor() #向下取整數
ceil() #向上取整數
fix() #向0的方向取整數

In [37]:
a = np.array([1.65, 1.55, -3.57, 2.0])
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [38]:
#下面例子是進行小數點第二位的 rounding，
#從 a[0] 和 a[1] 的 rounding 結果可以看出 IEEE 754 的"四捨五取最近偶數六入"。
np.round(a, decimals=1)

array([ 1.6,  1.6, -3.6,  2. ])

In [39]:
#下面例子是進行小數點第二位的 rounding，
#從 a[0] 和 a[1] 的 rounding 結果可以看出 IEEE 754 的"四捨五取最近偶數六入"。
# 這會印出 2
print(round(1.5)) #1.5進位=2; 1.5捨去=1; 取最近偶數

2


In [ ]:
#下面例子是進行小數點第二位的 rounding，
#從 a[0] 和 a[1] 的 rounding 結果可以看出 IEEE 754 的"四捨五取最近偶數六入"。
# 這也會印出 2
print(round(2.5)) #2.5進位=3; 2.5捨去=2; 取最近偶數

In [40]:
# Round至最近的整數
np.rint(a)

array([ 2.,  2., -4.,  2.])

In [41]:
# 無條件捨去小數點
np.trunc(a)

array([ 1.,  1., -3.,  2.])

In [42]:
# 向下取整數
np.floor(a)

array([ 1.,  1., -4.,  2.])

In [43]:
# 向上取整數
np.ceil(a)

array([ 2.,  2., -3.,  2.])

In [44]:
# 向0的方向取整數
np.fix(a)

array([ 1.,  1., -3.,  2.])

8. 取絕對值
np.abs() 
np.absolute() 
np.fabs()

In [45]:
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [46]:
#取絕對值
#np.abs() 
np.abs(a)

array([1.65, 1.55, 3.57, 2.  ])