順序統計量 (Order Statistics)
平均數與變異數
相關性
直方圖 (Histogram)

統計函式也須注意針對計算的軸 (axis) 與維度 (dimension)
直方圖 (Histogram) 需要配合套件 matplotlib.pyplot 使用

In [1]:
import numpy as np

1. 順序統計量 (Order Statistics)
1.1 最大值和最小值

In [3]:
np.random.seed(1)
a = np.random.randint(1, 10, 6).reshape(2, 3) #>=1 and <10; 取六組元素; 2*3陣列
b = np.random.randint(1, 5, 3) #>=1 and <5; 取三組元素

In [4]:
a

array([[6, 9, 6],
       [1, 1, 2]])

In [5]:
b

array([1, 4, 2])

1.1.1 numpy.maximum(), numpy.minimum()
以 element-wise 比較 2 個陣列並回傳各元素的最大值或最小值。
===>如果比較的元素中的 nan 的話，則會回傳 nan。
maximum() 與 minimum() 在進行比較時，若有需要會利用到廣播 (bradcasting)。

In [6]:
#numpy.maximum()
np.maximum(a, b)

array([[6, 9, 6],
       [1, 4, 2]])

In [7]:
#numpy.minimum()
np.minimum(a, b)

array([[1, 4, 2],
       [1, 1, 2]])

In [8]:
#如果比較的元素中的 nan 的話，則會回傳 nan
np.maximum(a, [np.nan, 0, np.nan])

array([[nan,  9., nan],
       [nan,  1., nan]])

1.1.2 numpy.fmax(), numpy.fmin()
以 element-wise 比較 2 個陣列並回傳各元素的最大值或最小值
===>比較的元素中只有一個是 nan 的話，回傳非 nan 的值
如果兩個元素都是 nan 則回傳 nan

In [9]:
#numpy.fmax()
np.fmax(a, b)

array([[6, 9, 6],
       [1, 4, 2]])

In [10]:
#numpy.fmin()
np.fmin(a, b)

array([[1, 4, 2],
       [1, 1, 2]])

In [11]:
#numpy.fmin()
#比較的元素中只有一個是 nan 的話，回傳非 nan 的值
np.fmin([np.nan, 3, np.nan], [np.nan, np.nan, np.nan])

array([nan,  3., nan])

1.1.3 numpy.nanmax(), numpy.nanmin()
====>回傳陣列中有非 nan 元素值的最大值或最小值
可以指定要比較的軸
回傳值是否要保留維度
#numpy.nanmax(a, axis=None, keepdims=<no value>)
#numpy.nanmin(a, axis=None, keepdims=<no value>)

In [12]:
#numpy.nanmax(a, axis=None, keepdims=<no value>)
#回傳陣列中有非 nan 元素值的最大值或最小值
np.nanmax([1, 2, np.nan, 3])

3.0

In [ ]:
1.2 百分位數
#percentile():計算百分位數 
#nanpercentile() :計算百分位數，忽略 nan
#numpy.percentile(a, q, axis=None, keepdims=<no value>) #可以指定要比較的軸;回傳值是否要保留維度
#numpy.nanpercentile(a, q, axis=None, keepdims=<no value>) #可以指定要比較的軸;回傳值是否要保留維度

In [13]:
p = np.arange(1, 20).astype('float32') #>=1 and <20
p

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [19]:
np.percentile(p, [10, 20, 30])

array([2.8, 4.6, 6.4])

In [22]:
np.percentile(p, 30)

6.3999999999999995

1.3 分位數：quantile(), nanquantile()
#quantile():計算分位數
#nanquantile():計算分位數，忽略 nan
#可以指定要比較的軸
#回傳值是否要保留維度
#numpy.quantile(a, q, axis=None, keepdims=<no value>)
#numpy.nanquantile(a, q, axis=None, keepdims=<no value>)

In [23]:
q = np.array([23,  2,  1, 18,  9, 25, 14, 48, 43,  9, 31,  8,  4,  7, 22,  4,  5, 25, 44, 13])
q

array([23,  2,  1, 18,  9, 25, 14, 48, 43,  9, 31,  8,  4,  7, 22,  4,  5,
       25, 44, 13])

In [26]:
np.quantile(q, 0.5)

13.5

In [27]:
q = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 48, 43,  9, 31,  np.nan,  4,  7, np.nan,  4,  5, 25, 44, 13])
q

array([23.,  2.,  1., nan,  9., 25., nan, 48., 43.,  9., 31., nan,  4.,
        7., nan,  4.,  5., 25., 44., 13.])

In [30]:
q = q.reshape(5, 4) #5*4陣列
q

array([[23.,  2.,  1., nan],
       [ 9., 25., nan, 48.],
       [43.,  9., 31., nan],
       [ 4.,  7., nan,  4.],
       [ 5., 25., 44., 13.]])

In [33]:
#沿 axis 0 計算分位數，並且保留二維的維度
np.nanquantile(q, 0.25, axis=0, keepdims=True)

array([[ 5. ,  7. , 16. ,  8.5]])

In [35]:
#沿 axis 0 計算分位數，並且保留二維的維度
np.nanquantile(q, 1, axis=0, keepdims=True)

array([[43., 25., 44., 48.]])

2. 平均數與變異數
2.1 平均值：mean(), nanmean()
#numpy.mean(a, axis=None, dtype=None, keepdims=<no value>) 
#numpy.nanmean(a, axis=None, dtype=None, keepdims=<no value>)
#指定要計算平均數的軸
#回傳值是否要保留維度
#dtype 引數是計算使用的型別

In [36]:
a = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 
              48, 43,  9, 31,  np.nan])
a

array([23.,  2.,  1., nan,  9., 25., nan, 48., 43.,  9., 31., nan])

In [39]:
a = a.reshape(3, 4) #3*4陣列
a

array([[23.,  2.,  1., nan],
       [ 9., 25., nan, 48.],
       [43.,  9., 31., nan]])

In [40]:
np.mean(a)

nan

In [42]:
if not np.isnan(np.sum(a)): #陣列中無 nan
    print("陣列中無 nan，忽略 nan 後的平均值為 :", np.mean(a))
else:
    print("陣列中有 nan，忽略 nan 後的平均值為 :", np.nanmean(a))

陣列中有 nan，忽略 nan 後的平均值為 : 21.22222222222222


2.2 平均值
#average()
#numpy.average(a, axis=None, weights=None)
#計算平均值的話，可以輸入權重值做為引數

In [43]:
a = np.arange(6).reshape(3, 2) #3*2陣列
a 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [44]:
#權重平均值的計算公式為
#avg = sum(a * weights) / sum(weights)
#numpy.average(a, axis=None, weights=None)
np.average(a, axis=1, weights=[0.25, 0.75]) #權重的總和不能為 0，否則會產生錯誤

array([0.75, 2.75, 4.75])

In [48]:
np.average(a, axis=1, weights=[3, 1])

array([0.25, 2.25, 4.25])

2.3 計算中位數
#median()
#nanmedian()
#numpy.median(a, axis=None, keepdims=False)
#numpy.nanmedian(a, axis=None, keepdims=False)

In [50]:
np.random.seed(5)
m = np.random.randint(1, 50, 15).reshape(3, 5) #>=1 and <50; 挑15組; 3*5陣列
m

array([[36, 15, 48, 39, 17],
       [10,  9, 37, 40, 28],
       [49, 31, 17,  8, 13]])

In [53]:
#numpy.median(a, axis=None, keepdims=False)
np.median(m, axis=1, keepdims=True)

array([[36.],
       [28.],
       [17.]])

In [54]:
#numpy.median(a, axis=None, keepdims=False)
np.median(m, axis=0, keepdims=True)

array([[36., 15., 37., 39., 17.]])

2.4 計算標準差
#std() 
#nanstd()
#numpy.std(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
#numpy.nanstd(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
如果要計算樣本標準差的話，可將 ddof (自由度) 引數傳入 1，在計算平均方差 (mean squared deviation) 時分母就會以 N - ddof 做計算。

In [55]:
s = np.array([[1, 2], [3, 4]])
s

array([[1, 2],
       [3, 4]])

In [56]:
#numpy.std(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
np.std(s)

1.118033988749895

2.5 計算變異數
#var()
#nanvar()
對於精度可能造成的誤差影響，可以改變 dtype 提高精度
#numpy.var(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
#numpy.nanvar(a, axis=None, dtype=None, ddof=0, keepdims=<no value>

In [57]:
v = np.array([[1, 2], [3, 4]])
v

array([[1, 2],
       [3, 4]])

In [58]:
#numpy.var(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
np.var(a)

2.9166666666666665

In [59]:
#numpy.var(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
np.var(a, axis=0)

array([2.66666667, 2.66666667])

In [60]:
#numpy.var(a, axis=None, dtype=None, ddof=0, keepdims=<no value>)
np.var(a, axis=1)

array([0.25, 0.25, 0.25])

In [ ]:
3. 相關性
3.1 相關係數
#corrcoef()
計算 Pearson 積差相關係數
引數 rowvar 預設值為 True，代表將每一個 row 當做是一筆變數
#numpy.corrcoef(x, y=None, rowvar=True)

In [63]:
#numpy.corrcoef(x, y=None, rowvar=True)
x = np.random.randint(1, 20, 10).reshape(2, 5) #>=1 and <20;挑選10組; 2*5陣列
np.corrcoef(x)

array([[1.        , 0.64936333],
       [0.64936333, 1.        ]])