In [1]:
import numpy as np

In [6]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30)) 

#轉成維度為(5X6)的array
array1.reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [7]:
#順序按列填充。(hint:order="F")
#按列排序
array1.ravel(order='F')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
#2.呈上題的array，找出被6除餘1的數的索引
#numpy.where(condition[, x, y])
#傳入條件式，回傳值為符合條件的元素索引
np.where(array1 % 6 ==1)

(array([ 1,  7, 13, 19, 25], dtype=int64),)